routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


Route::view('/blocked','errors.403');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Our resource routes
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);

    // User Status
    Route::get('/search', [UserController::class,'search'])->name('search');
    Route::post('/UserBlock',[UserController::class,'UserBlock'])->name('UserBlock');

});

require __DIR__.'/auth.php';

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controllers\Middleware;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{

    public static function middleware(): array
    {
        return [
            new Middleware('permission:role-list|role-create|role-edit|role-delete', only: ['index', 'store']),
            new Middleware('permission:role-create', only: ['create', 'store']),
            new Middleware('permission:role-edit', only: ['edit', 'update']),
            new Middleware('permission:role-delete', only: ['destroy']),
        ];
    }

    public function index(Request $request)
    {
        $roles = Role::orderBy('id', 'DESC')->paginate(5);
        return view('roles.index', compact('roles'));
    }

    public function create()
    {
        $permission = Permission::get();
        return view('roles.create', compact('permission'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

//        dd($request->input('permission'));

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
            ->with('success', 'Role created successfully');
    }

    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions", "role_has_permissions.permission_id", "=", "permissions.id")
            ->where("role_has_permissions.role_id", $id)
            ->get();

        return view('roles.show', compact('role', 'rolePermissions'));
    }

    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id", $id)
            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
            ->all();

        return view('roles.edit', compact('role', 'permission', 'rolePermissions'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
            ->with('success', 'Role updated successfully');
    }

    public function destroy($id)
    {
        DB::table("roles")->where('id', $id)->delete();
        return redirect()->route('roles.index')
            ->with('success', 'Role deleted successfully');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.appDash')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb mb-4">
            <div class="pull-left">
                <h2>
                    <div class="float-end">
                        <a class="btn bg-danger-subtle text-danger" href="{{ route('roles.index') }}"> Back</a>
                    </div>
                </h2>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('roles.store') }}" method="POST">
        @csrf




        <div class="card">
            <div class="card-header text-bg-primary">
                <h5 class="mb-0 text-white">Create New Role</h5>
            </div>
            <div class="px-4 py-3 border-bottom">
                <h4 class="card-title mb-0"></h4>
            </div>
            <div class="card-body p-4 border-bottom">
                <div class="row">
                    <div class="col-lg-6 ">
                        <div class="mb-4">
                            <label class="form-label">Name:</label>
                            <div class="input-group">
                                <input type="text" name="name" class="form-control" placeholder="Name">
                            </div>
                        </div>
                        <div>
                            <label class="form-label">Permission:</label>
                            <br>
                                @foreach ($permission as $value)
                                    <label>
                                        <input type="checkbox" name="permission[]" value="{{ $value->name }}" class="name">
                                        {{ $value->name }}</label>
                                    <br />
                                @endforeach
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-flex justify-content-center gap-3">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </div>
            </div>
        </div>

    </form>


@endsection

resources/views/roles/edit.blade.php
@extends('layouts.appDash')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb mb-4">
            <div class="pull-left">
                <h2>
                    <div class="float-end">
                        <a class="btn bg-danger-subtle text-danger" href="{{ route('roles.index') }}"> Back</a>
                    </div>
                </h2>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('roles.update', $role->id) }}" method="POST">
        @method('PATCH')
        @csrf

        <div class="card">
            <div class="card-header text-bg-primary">
                <h5 class="mb-0 text-white">Edit Role</h5>
            </div>
            <div class="px-4 py-3 border-bottom">
                <h4 class="card-title mb-0"></h4>
            </div>
            <div class="card-body p-4 border-bottom">
                <div class="row">
                    <div class="col-lg-6 ">
                        <div class="mb-4">
                            <label class="form-label">Name:</label>
                            <div class="input-group">
                                <input type="text" name="name" value="{{ $role->name }}" class="form-control" placeholder="Name">
                            </div>
                        </div>
                        <div>
                            <label class="form-label">Permission:</label>
                            <br>
                            @foreach ($permission as $value)
                                <label>
                                    <input type="checkbox" @if (in_array($value->id, $rolePermissions)) checked @endif name="permission[]"
                                           value="{{ $value->name }}" class="name">
                                    {{ $value->name }}</label>
                                <br />
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-flex justify-content-center gap-3">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


@endsection

resources/views/roles/index.blade.php
@extends('layouts.appDash')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb mb-4">
            <div class="pull-left">
                <h5>Role Management
                    <div class="float-end">
{{--                        @can('role-create')--}}
{{--                            <a class="btn btn-success" href="{{ route('roles.create') }}"> Create New Role</a>--}}
                            <a href="{{ route('roles.create') }}" class="btn bg-success-subtle text-success btn-sm" title="View Code"
                                {{--                            data-bs-toggle="modal" data-bs-target="#view-code2-modal"--}}
                            >
                                <iconify-icon icon="solar:add-circle-broken" width="30" height="30"></iconify-icon>
                                Create New Role
                            </a>
{{--                        @endcan--}}
                    </div>
                </h5>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table text-nowrap customize-table mb-0 align-middle table-hover">
        <tr>
            <th>
                <h6 class="fs-4 fw-semibold mb-0">Name</h6>
            </th>
            <th width="280px">
                <h6 class="fs-4 fw-semibold mb-0 text-center">Action</h6>
            </th>
        </tr>
        @foreach ($roles as $key => $role)
            <tr>
                <td>{{ $role->name }}</td>
                <td>
                    <form action="{{ route('roles.destroy', $role->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('roles.show', $role->id) }}">Show</a>
{{--                        @can('role-edit')--}}
                            <a class="btn btn-primary" href="{{ route('roles.edit', $role->id) }}">Edit</a>
{{--                        @endcan--}}


                        @csrf
                        @method('DELETE')
{{--                        @can('product-delete')--}}
                            <button type="submit" class="btn btn-danger">Delete</button>
{{--                        @endcan--}}
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

    @if(!isset($paginate))
        <div class="d-flex justify-content-center my-4">
            {!! $roles->links() !!}
        </div>
    @endif

{{--    {!! $roles->render() !!}--}}
@endsection

resources/views/roles/show.blade.php
@extends('layouts.appDash')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb mb-4">
            <div class="pull-left">
                <h2>
                    <div class="float-end">
                        <a class="btn bg-danger-subtle text-danger" href="{{ route('roles.index') }}"> Back</a>
                    </div>
                </h2>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header text-bg-primary">
            <h5 class="mb-0 text-white">View Role</h5>
        </div>
        <form class="form-horizontal">
            <div class="form-body">
                <div class="card-body">
                </div>
                <hr class="m-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="form-label text-end col-md-3"> Name:</label>
                                <div class="col-md-9">
                                    <p class="form-control-static">{{ $role->name }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="form-label text-end col-md-3">Permission:</label>
                                <div class="col-md-9">
                                    @if (!empty($rolePermissions))
                                        @foreach ($rolePermissions as $v)
                                            <p class="form-control-static">{{ $v->name }},</p>

                                        @endforeach
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <hr class="m-0">
                <div class="card-body">
                </div>
            </div>
        </form>
    </div>

@endsection